-- begin TIMEMANAGER_TIME_ZONE_OFFSET
create unique index IDX_TIMEMANAGER_TIME_ZONE_OFFSET_UK_NAME on TIMEMANAGER_TIME_ZONE_OFFSET (NAME) where DELETE_TS is null ^
-- end TIMEMANAGER_TIME_ZONE_OFFSET
-- begin TIMEMANAGER_ZONE_ENTRY
alter table TIMEMANAGER_ZONE_ENTRY add constraint FK_TIMEMANAGER_ZONE_ENTRY_ON_ZONE_OFFSET foreign key (ZONE_OFFSET_ID) references TIMEMANAGER_TIME_ZONE_OFFSET(ID)^
create unique index IDX_TIMEMANAGER_ZONE_ENTRY_UK_NAME on TIMEMANAGER_ZONE_ENTRY (NAME) where DELETE_TS is null ^
create index IDX_TIMEMANAGER_ZONE_ENTRY_ON_ZONE_OFFSET on TIMEMANAGER_ZONE_ENTRY (ZONE_OFFSET_ID)^
-- end TIMEMANAGER_ZONE_ENTRY
